### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by blerude** [danielle-h/bapi-p3-the-scoop#4]
Grade: Exceeds Expectations

This is an exceptional take on the assignment. Not only is your code effective and efficient in completing the purpose of each function, but it is also incredibly easy to read. Your programming conventions of code alignment/organization, as well as your habit of commenting each function, make it so simple to follow along with the flow of your work. It's clear that you understand how someone would go about interpreting the code, and that you took that into account while working. I'm also glad that you took on the bonus! 

Moving forward, you have the skills to take projects on in your own style. Your instinct to give names to the status codes was spot on! Feel free to follow through with those instincts in the future. A general rule in coding is that if you can find a better, clearer, or more sophisticated way to program something, do it! Again, great job and congratulations!

**Comment by danielle-h** [comment]
Thank you!
